"""add cms testimonials

Revision ID: 093e4a609650
Revises: 155febe61f20
Create Date: 2026-09-03 03:40:58.392253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093e4a609650'
down_revision: Union[str, Sequence[str], None] = '155febe61f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_testimonials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_testimonials_id'), 'cms_testimonials', ['id'], unique=False)
    op.create_index(op.f('ix_cms_testimonials_tenant_id'), 'cms_testimonials', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cms_testimonials_tenant_id'), table_name='cms_testimonials')
    op.drop_index(op.f('ix_cms_testimonials_id'), table_name='cms_testimonials')
    op.drop_table('cms_testimonials')
    # ### end Alembic commands ###
