"""add notes to expenses

Revision ID: 3c4fecbc1a1d
Revises: 67c8b2b65061
Create Date: 2026-08-06 23:40:24.885364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c4fecbc1a1d'
down_revision: Union[str, Sequence[str], None] = '67c8b2b65061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('notes', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'notes')
    # ### end Alembic commands ###
