"""add outstanding module

Revision ID: 3ca3382e6560
Revises: 561052a44870
Create Date: 2026-08-07 06:40:00.672744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ca3382e6560'
down_revision: Union[str, Sequence[str], None] = '561052a44870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outstandings',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('total_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('outstanding_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outstandings_id'), 'outstandings', ['id'], unique=False)
    op.create_index(op.f('ix_outstandings_patient_id'), 'outstandings', ['patient_id'], unique=False)
    op.create_index(op.f('ix_outstandings_tenant_id'), 'outstandings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_outstandings_visit_id'), 'outstandings', ['visit_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outstandings_visit_id'), table_name='outstandings')
    op.drop_index(op.f('ix_outstandings_tenant_id'), table_name='outstandings')
    op.drop_index(op.f('ix_outstandings_patient_id'), table_name='outstandings')
    op.drop_index(op.f('ix_outstandings_id'), table_name='outstandings')
    op.drop_table('outstandings')
    # ### end Alembic commands ###
