"""add email and message to leads

Revision ID: 6f274499d698
Revises: b765a21966c9
Create Date: 2026-09-11 00:26:09.710523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f274499d698'
down_revision: Union[str, Sequence[str], None] = 'b765a21966c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'message')
    op.drop_column('leads', 'email')
    # ### end Alembic commands ###
