"""create treatment photos table

Revision ID: 8e63d66164c8
Revises: e33635ebe889
Create Date: 2026-08-06 03:07:19.750827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e63d66164c8'
down_revision: Union[str, Sequence[str], None] = 'e33635ebe889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment_photos',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('photo_type', sa.Enum('BEFORE', 'AFTER', name='phototype', native_enum=False), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_photos_id'), 'treatment_photos', ['id'], unique=False)
    op.create_index(op.f('ix_treatment_photos_tenant_id'), 'treatment_photos', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_treatment_photos_visit_id'), 'treatment_photos', ['visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_treatment_photos_visit_id'), table_name='treatment_photos')
    op.drop_index(op.f('ix_treatment_photos_tenant_id'), table_name='treatment_photos')
    op.drop_index(op.f('ix_treatment_photos_id'), table_name='treatment_photos')
    op.drop_table('treatment_photos')
    # ### end Alembic commands ###
