"""add cms services

Revision ID: d8b5ffb50be7
Revises: 314fb2e7a9ce
Create Date: 2026-08-31 02:46:23.543776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8b5ffb50be7'
down_revision: Union[str, Sequence[str], None] = '314fb2e7a9ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_outstandings_visit_id'), table_name='outstandings')
    op.create_unique_constraint(None, 'outstandings', ['visit_id'])
    op.drop_constraint(op.f('staff_employee_code_key'), 'staff', type_='unique')
    op.drop_constraint(op.f('staff_user_id_key'), 'staff', type_='unique')
    op.create_index(op.f('ix_staff_employee_code'), 'staff', ['employee_code'], unique=True)
    op.create_index(op.f('ix_staff_user_id'), 'staff', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_user_id'), table_name='staff')
    op.drop_index(op.f('ix_staff_employee_code'), table_name='staff')
    op.create_unique_constraint(op.f('staff_user_id_key'), 'staff', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('staff_employee_code_key'), 'staff', ['employee_code'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'outstandings', type_='unique')
    op.create_index(op.f('ix_outstandings_visit_id'), 'outstandings', ['visit_id'], unique=True)
    op.create_table('leads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'new'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('leads_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('leads_pkey'))
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    # ### end Alembic commands ###
